// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFEpykC3q7-rWwfYx78yWy0Odz1mbWE0U',
    appId: '1:1031417987351:web:46f9cde866544cef49f752',
    messagingSenderId: '1031417987351',
    projectId: 'fitnessprojectmaster',
    authDomain: 'fitnessprojectmaster.firebaseapp.com',
    storageBucket: 'fitnessprojectmaster.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM9JsWPiGO7XDexxDTbO_cy5DaJ7zo4ow',
    appId: '1:1031417987351:android:5fd2a9cf6323763649f752',
    messagingSenderId: '1031417987351',
    projectId: 'fitnessprojectmaster',
    storageBucket: 'fitnessprojectmaster.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAovp0FUcacQA3F6NzCKotanC_IAu4HlYo',
    appId: '1:1031417987351:ios:c729f471f90fe17249f752',
    messagingSenderId: '1031417987351',
    projectId: 'fitnessprojectmaster',
    storageBucket: 'fitnessprojectmaster.appspot.com',
    androidClientId: '1031417987351-1hutk3tm9q118ohlfjrd7ksda1h775h5.apps.googleusercontent.com',
    iosClientId: '1031417987351-nqnr333gmnus81t0subkd6ne94kgktbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAovp0FUcacQA3F6NzCKotanC_IAu4HlYo',
    appId: '1:1031417987351:ios:c729f471f90fe17249f752',
    messagingSenderId: '1031417987351',
    projectId: 'fitnessprojectmaster',
    storageBucket: 'fitnessprojectmaster.appspot.com',
    androidClientId: '1031417987351-1hutk3tm9q118ohlfjrd7ksda1h775h5.apps.googleusercontent.com',
    iosClientId: '1031417987351-nqnr333gmnus81t0subkd6ne94kgktbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
